-- MySQL Script generated by MySQL Workbench
-- Thu May 25 17:19:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `funcionario_id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_nome` VARCHAR(255) NOT NULL,
  `funcionario_login` VARCHAR(64) NOT NULL,
  `funcionario_senha` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`funcionario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `produto_id` INT NOT NULL,
  `produto_nome` VARCHAR(255) NOT NULL,
  `produto_descricao` TEXT NULL,
  `produto_preco` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`produto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(255) NOT NULL,
  `cliente_telefone` VARCHAR(45) NOT NULL,
  `cliente_endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinhos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carrinhos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carrinhos` (
  `carrinho_id` INT NOT NULL,
  `Clientes_cliente_id` INT NOT NULL,
  PRIMARY KEY (`carrinho_id`),
  CONSTRAINT `fk_Carrinhos_Clientes1`
    FOREIGN KEY (`Clientes_cliente_id`)
    REFERENCES `mydb`.`Clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carrinhos_Clientes1_idx` ON `mydb`.`Carrinhos` (`Clientes_cliente_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `pedido_id` INT NOT NULL,
  `Produtos_produto_id` INT NOT NULL,
  `Carrinhos_carrinho_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`),
  CONSTRAINT `fk_Pedidos_Produtos1`
    FOREIGN KEY (`Produtos_produto_id`)
    REFERENCES `mydb`.`Produtos` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Carrinhos1`
    FOREIGN KEY (`Carrinhos_carrinho_id`)
    REFERENCES `mydb`.`Carrinhos` (`carrinho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Produtos1_idx` ON `mydb`.`Pedidos` (`Produtos_produto_id` ASC);

CREATE INDEX `fk_Pedidos_Carrinhos1_idx` ON `mydb`.`Pedidos` (`Carrinhos_carrinho_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
